version: '3'
services:
    database:
        build:
            context: .
            dockerfile: ./database/Dockerfile
        image: sayukiki/shorturldatabase
        container_name: shorturldatabase
        restart: always

    webapps:
        build:
            context: .
            dockerfile: ./webapps/Dockerfile
        image: sayukiki/shorturlwebapps
        container_name: shorturlwebapps
        restart: always
        depends_on:
            - "database"
        ports:
            - 80:8000
        environment:
            ROOT_URL: $ROOT_URL
            STR_LENGTH: $STR_LENGTH
            EXPIRE: $EXPIRE
            POOL_MIN_SIZE: $POOL_MIN_SIZE
            POOL_MAX_SIZE: $POOL_MAX_SIZE
